"""App-generated activity log for handoffs: exact commands, file operations and
tool calls taken from a conversation's saved display history.

The app writes this text itself, so the model spends no output tokens on it and
the log also covers turns that compaction removed from the model's context.
"""
import json
import os
import re
from collections import Counter, defaultdict
from datetime import datetime

from .tools import LIMIT


ACTIVITY_TOOL = "insert_activity_log"
ACTIVITY_MARKER = "<!-- activity-log -->"
MAX_COMMAND_CHARS = 4000
MAX_PATHS_PER_GROUP = 200
FILE_GROUPS = (
    ("write_file", "Created or replaced"), ("edit_file", "Edited"), ("read_file", "Read"),
    ("list_files", "Listed"), ("search_files", "Searched"),
)
# Commands are copied as they ran. Besides the app's configured credentials,
# replace values that match common secret shapes before writing them to a file.
SECRET_PATTERNS = (
    (re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})"), "[REDACTED]"),
    (re.compile(r"\bdapi[0-9a-f]{32}(?:-\d+)?\b"), "[REDACTED]"),
    (re.compile(r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b"), "[REDACTED]"),
    (re.compile(r"(?i)(\b(?:bearer|basic|token)\s+)(?!\$)[A-Za-z0-9._~+/=-]{16,}"), r"\1[REDACTED]"),
    (re.compile(r"(?i)\b([a-z0-9_]*(?:password|passwd|secret|token|api[-_]?key|access[-_]?key)[a-z0-9_]*)"
                r"(\s*[=:]\s*)(['\"]?)(?!\$)[^\s'\"&;|]+\3"), r"\1\2\3[REDACTED]\3"),
    (re.compile(r"(://[^/\s:@]+:)[^@\s/]+@"), r"\1[REDACTED]@"),
)


def redact_secrets(text):
    for pattern, replacement in SECRET_PATTERNS:
        text = pattern.sub(replacement, text)
    return text


def local_time(timestamp):
    try:
        return datetime.fromtimestamp(float(timestamp)).astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
    except (TypeError, ValueError, OverflowError, OSError):
        return "unknown time"


def _fence(text):
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    return "`" * max(3, longest + 1)


def _absolute(path, workspace):
    if not isinstance(path, str) or not path:
        return str(workspace)
    expanded = os.path.expanduser(path)
    return os.path.normpath(expanded if os.path.isabs(expanded) else os.path.join(workspace, expanded))


def _output_json(event):
    try:
        value = json.loads(event.get("output") or "")
    except (TypeError, ValueError):
        return {}
    return value if isinstance(value, dict) else {}


def _command_result(event, jobs):
    state = event.get("state")
    if state == "rejected":
        return "declined or blocked"
    if state in ("error", "cancelled"):
        first_line = (event.get("output") or "").strip().splitlines()[:1]
        return state + (f": {first_line[0][:200]}" if first_line else "")
    details = _output_json(event)
    job = jobs.get(event.get("job_id") or details.get("job_id")) or {}
    job_state = job.get("state") or event.get("job_state") or details.get("state") or state or "unknown"
    exit_code = job.get("exit_code", details.get("exit_code"))
    result = str(job_state).replace("_", " ")
    if type(exit_code) is int:
        result += f", exit {exit_code}"
    if job.get("background", details.get("background")):
        result += ", background job"
    return result


def _render(session, commands, file_groups, others, declined, omitted, redact):
    title = redact(str(session.get("title") or "untitled"))
    lines = [
        "## Activity log (generated by the app)", "",
        f"Generated {local_time(datetime.now().timestamp())} from conversation `{session.get('id', '')}` "
        f"(\"{title}\"), including turns that were later compacted. Values matching common secret "
        "patterns and the app's configured credentials are shown as [REDACTED].", "",
        f"### Commands run ({len(commands) + omitted})", "",
    ]
    if omitted:
        lines += [f"{omitted} earlier commands were omitted to stay within the 80 KB file limit. "
                  "Insert the log into a separate file to include every command.", ""]
    if not commands and not omitted:
        lines += ["None.", ""]
    for number, (event, text, result) in enumerate(commands, start=omitted + 1):
        fence = _fence(text)
        lines += [f"**{number}.** {local_time(event.get('created'))} · {result}", "", fence + "bash", text, fence, ""]
    lines += ["### Files", ""]
    if not any(file_groups.values()):
        lines += ["None.", ""]
    for name, label in FILE_GROUPS:
        paths = file_groups.get(name)
        if not paths:
            continue
        lines.append(f"**{label}** (`{name}`):")
        items = sorted(paths.items())
        for path, count in items[:MAX_PATHS_PER_GROUP]:
            lines.append(f"- `{redact(path)}`" + (f" ({count} times)" if count > 1 else ""))
        if len(items) > MAX_PATHS_PER_GROUP:
            lines.append(f"- ... and {len(items) - MAX_PATHS_PER_GROUP} more")
        lines.append("")
    if declined:
        lines += ["### Declined, blocked, or failed actions", ""]
        lines += [f"- {local_time(event.get('created'))} · `{event.get('name')}` "
                  f"`{redact(summary)}` · {event.get('state')}" for event, summary in declined]
        lines.append("")
    lines += ["### Other tool calls", ""]
    lines += [f"- `{name}`: {count}" for name, count in sorted(others.items())] or ["None."]
    if others.get("delegate_task"):
        lines.append("- Delegated subagent conversations keep their own activity; open them to log their commands.")
    lines.append("")
    return "\n".join(lines)


def activity_log(session, jobs=None, *, exclude_event_id=None, redact=lambda text: text, max_bytes=LIMIT):
    """Render the log and statistics, omitting the oldest commands if needed to fit max_bytes."""
    jobs = {job["id"]: job for job in (jobs or []) if isinstance(job, dict) and job.get("id")}
    workspace = session.get("workspace") or "."
    clean = lambda text: redact(redact_secrets(text))
    commands, declined = [], []
    file_groups, others = defaultdict(Counter), Counter()
    for event in session.get("events", []):
        if not isinstance(event, dict) or event.get("type") != "tool" or event.get("id") == exclude_event_id:
            continue
        name, arguments = event.get("name") or "tool", event.get("input") if isinstance(event.get("input"), dict) else {}
        if name == "run_command":
            text = clean(str(arguments.get("command", "")))
            if len(text) > MAX_COMMAND_CHARS:
                text = text[:MAX_COMMAND_CHARS] + f"\n# ... command truncated ({len(text):,} characters)"
            commands.append((event, text, _command_result(event, jobs)))
        elif name in dict(FILE_GROUPS):
            if event.get("state") == "completed":
                file_groups[name][_absolute(arguments.get("path", "."), workspace)] += 1
            else:
                declined.append((event, _absolute(arguments.get("path", "."), workspace)))
        else:
            others[name] += 1
    omitted, low, high = 0, 0, len(commands)
    text = _render(session, commands, file_groups, others, declined, 0, clean)
    if len(text.encode("utf-8")) > max_bytes:
        # Keep the most recent commands: find the fewest omissions that fit.
        while low < high:
            middle = (low + high) // 2
            candidate = _render(session, commands[middle:], file_groups, others, declined, middle, clean)
            if len(candidate.encode("utf-8")) <= max_bytes:
                high = middle
            else:
                low = middle + 1
        omitted = low
        text = _render(session, commands[omitted:], file_groups, others, declined, omitted, clean)
        if len(text.encode("utf-8")) > max_bytes:
            raise ValueError("The activity log does not fit in this file. Insert it into a separate, new file.")
    stats = {"commands": len(commands), "commands_omitted": omitted,
             "files": sum(len(paths) for paths in file_groups.values()),
             "other_tool_calls": sum(others.values()), "declined_or_failed": len(declined)}
    return text, stats


def insert_log(original, log):
    """Return new file content with the log at the marker, or appended."""
    if original is None:
        return log, "new file"
    count = original.count(ACTIVITY_MARKER)
    if count > 1:
        raise ValueError(f"The file contains {ACTIVITY_MARKER} more than once; keep exactly one.")
    if count == 1:
        return original.replace(ACTIVITY_MARKER, log.rstrip("\n"), 1), "marker"
    return original.rstrip("\n") + "\n\n" + log, "appended"


def activity_content(session, original, jobs=None, *, exclude_event_id=None, redact=lambda text: text):
    base = "" if original is None else original.replace(ACTIVITY_MARKER, "", 1)
    budget = LIMIT - len(base.encode("utf-8")) - 2
    if budget < 1000:
        raise ValueError("The file is too close to the 80 KB limit for an activity log. Insert it into a separate, new file.")
    log, stats = activity_log(session, jobs, exclude_event_id=exclude_event_id, redact=redact, max_bytes=budget)
    content, placement = insert_log(original, log)
    return content, {**stats, "placement": placement, "bytes_added": len(log.encode("utf-8"))}
